# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:latest
    environment: GO111MODULE=on
    steps:
      - run:
          name: Install Gomason
          command: go get github.com/nikogura/gomason
      - run:
          name: Initialize GPG Agent
          command: gpg-agent --daemon
      - checkout
      - run:
          name: Run Tests
          command: gomason test -v -b ${CIRCLE_BRANCH}

  publish:
    docker:
      - image: circleci/golang:latest
    environment: GO111MODULE=on
    steps:
      - run:
          name: Install Gomason
          command: go get github.com/nikogura/gomason
      - run:
          name: Initialize GPG Agent
          command: gpg-agent --daemon
      - run:
          name: Install Expect
          command: sudo apt install -y expect
      - checkout
      - run:
          name: Stage SSH Key
          command: echo "$OPS_SSH_KEY" | base64 -d > ~/.ssh/id_rsa.ops && chmod 600 ~/.ssh/id_rsa.ops
      - run:
          name: Stage Keyscript
          command: echo "$KEYSCRIPT" > keyscript.sh
      - run:
          name: Load SSH Key into Agent
          command: ./keyscript.sh
      - run:
          name: Stage Signing Key
          command: |
            echo "$SIGNING_PRIVATE_KEY" | base64 -d > obci@orionlabs.asc
      - run:
          name: Import Signing Key
          command: gpg --import obci@orionlabs.asc
      - run:
          name: Publish
          command: gomason publish -v

workflows:
  version: 2
  primary:
    jobs:
#      - test:
#          filters:
#            branches:
#              ignore:
#                - master
      - publish:
          filters:
            branches:
              only:
                - master
